### PR TITLE
101313726 add new relic

### PR DESCRIPTION
**Pull request by TheNotTooDistantFuture**
Adding the New Relic agent to Looker

### CODE REVIEW

**Comment by roboshopkeep** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins-devops-mesos.posrip.com//job/cookbook-looker/1/
Specs Pass! :+1:

**Comment by roboshopkeep** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins-devops-mesos.posrip.com//job/cookbook-looker/2/
Specs Pass! :+1:

**Comment by johnjmaguire** [comment]
Do you need the newrelic.yml file? You don't seem to be actually dropping it onto the machine and afaik it's only used for application monitoring (i.e. the application needs to be written to use it), not server monitoring.

**Comment by TheNotTooDistantFuture** [comment]
You're right - it was left over from copying how the ecommerce cookbook installed NewRelic. It's not needed this way

**Comment by roboshopkeep** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins-devops-mesos.posrip.com//job/cookbook-looker/3/
Specs Pass! :+1:

**Comment by TheNotTooDistantFuture** [comment]
Just to note - I set the chef_environment to staging in the metadata for testing this on stage. I'm sure we'll only need this on Production.
+include_recipe 'looker::_newrelic' if node.chef_environment.downcase.include? 'staging'

**Comment by johnjmaguire** [comment]
So shouldn't you set that if case to production before deploying?

**Comment by davidsayers** [comment]
this is a public cookbook. This shouldn't go in here.
Is there anything sensitive in the encrypted data bag?

**Comment by TheNotTooDistantFuture** [comment]
@johnjmaguire Yeah I was planning on changing it before going to Production after testing on Staging
@davidsayers Just the license key for New Relic

**Pull request closed without merging**
